-- Adicionar colunas para DURATION_SECONDS, EXECUTION_ORDER, STARTED_AT, ENDED_AT em CTL_LOAD_AUDIT
ALTER TABLE SOLIX_BI.DS.CTL_LOAD_AUDIT
ADD COLUMN EXECUTION_ORDER NUMBER(38,0) DEFAULT NULL;

ALTER TABLE SOLIX_BI.DS.CTL_LOAD_AUDIT
ADD COLUMN DURATION_SECONDS NUMBER(38,0) DEFAULT NULL;

ALTER TABLE SOLIX_BI.DS.CTL_LOAD_AUDIT
ADD COLUMN STARTED_AT TIMESTAMP_NTZ DEFAULT NULL;

ALTER TABLE SOLIX_BI.DS.CTL_LOAD_AUDIT
ADD COLUMN ENDED_AT TIMESTAMP_NTZ DEFAULT NULL;

-- Ex: EXECUTION_ORDER = sequência do step dentro do batch (1, 2, 3, ...)
-- Ex: DURATION_SECONDS = DATEDIFF(SECOND, STARTED_AT, ENDED_AT)
-- Ex: STARTED_AT = moment que o step iniciou
-- Ex: ENDED_AT = moment que o step terminou (sucesso ou erro)
