-- Adicionar colunas para DURATION_SECONDS e ORCHESTRATION_TYPE em CTL_BATCH_EXECUTION
ALTER TABLE SOLIX_BI.DS.CTL_BATCH_EXECUTION
ADD COLUMN DURATION_SECONDS NUMBER(38,0) DEFAULT NULL;

ALTER TABLE SOLIX_BI.DS.CTL_BATCH_EXECUTION
ADD COLUMN ORCHESTRATION_TYPE VARCHAR(50) DEFAULT NULL;

-- Ex: DURATION_SECONDS = DATEDIFF(SECOND, STARTED_AT, ENDED_AT)
-- Ex: ORCHESTRATION_TYPE = 'SCHEDULER', 'MANUAL_TRIGGER', 'API_TRIGGER', 'DBT_TRIGGER'

-- Remover colunas que nao fazem mais sentido no fluxo global atual
ALTER TABLE SOLIX_BI.DS.CTL_BATCH_EXECUTION DROP COLUMN IF EXISTS ID_CLIENTE;

ALTER TABLE SOLIX_BI.DS.CTL_BATCH_EXECUTION DROP COLUMN IF EXISTS DT_INICIO;

ALTER TABLE SOLIX_BI.DS.CTL_BATCH_EXECUTION DROP COLUMN IF EXISTS DT_FIM;
