import os
from dotenv import load_dotenv

load_dotenv()

class Settings:
    POSTGRES_HOST = os.getenv("POSTGRES_HOST")
    POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", "5432"))
    POSTGRES_DATABASE = os.getenv("POSTGRES_DATABASE")
    POSTGRES_USER = os.getenv("POSTGRES_USER")
    POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
    POSTGRES_SCHEMA = os.getenv("POSTGRES_SCHEMA", "public")

    ORACLE_DRIVER_MODE = os.getenv("ORACLE_DRIVER_MODE", "auto").strip().lower()
    ORACLE_HOST = os.getenv("ORACLE_HOST")
    ORACLE_PORT = int(os.getenv("ORACLE_PORT", "1521"))
    ORACLE_SERVICE = os.getenv("ORACLE_SERVICE")
    ORACLE_USER = os.getenv("ORACLE_USER")
    ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
    ORACLE_CLIENT_LIB_DIR = os.getenv("ORACLE_CLIENT_LIB_DIR")

    SNOWFLAKE_ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
    SNOWFLAKE_USER = os.getenv("SNOWFLAKE_USER")
    SNOWFLAKE_PRIVATE_KEY_PATH = os.getenv("SNOWFLAKE_PRIVATE_KEY_PATH")
    SNOWFLAKE_PRIVATE_KEY_PASSPHRASE = os.getenv("SNOWFLAKE_PRIVATE_KEY_PASSPHRASE")
    SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE")
    SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE")
    SNOWFLAKE_SCHEMA = os.getenv("SNOWFLAKE_SCHEMA")
    SNOWFLAKE_ROLE_INGESTAO = os.getenv("SNOWFLAKE_ROLE_INGESTAO") or os.getenv("SNOWFLAKE_ROLE")
    SNOWFLAKE_ROLE_DBT = os.getenv("SNOWFLAKE_ROLE_DBT") or os.getenv("SNOWFLAKE_ROLE")

    SNOWFLAKE_STAGE = os.getenv("SNOWFLAKE_STAGE")
    SNOWFLAKE_FILE_FORMAT = os.getenv("SNOWFLAKE_FILE_FORMAT")
