create table if not exists SOLIX_BI.DS.SX_DETALHES_OPERACAO_F (
    ID_CLIENTE number(38, 0) not null,
    DT_DIA_FECHAMENTO date not null,
    DATA date not null,
    HORA number(38, 0) not null,
    CD_EQUIPAMENTO number(38, 0) not null,
    CD_GRUPO_EQUIPAMENTO number(38, 0) not null,
    CD_OPERACAO number(38, 0) not null,
    CD_OPERACAO_CB number(38, 0) not null,
    CD_ORDEM_SERVICO number(38, 0),
    CD_UNIDADE number(38, 0) not null,
    CD_REGIONAL number(38, 0) not null,
    CD_CORPORATIVO number(38, 0) not null,
    CD_FAZENDA number(38, 0) not null,
    CD_ZONA number(38, 0) not null,
    CD_TALHAO number(38, 0) not null,
    CD_MISSAO number(38, 0) not null,
    CD_ESTADO varchar(50) not null,
    VL_TEMPO_SEGUNDOS number(38, 6),
    VL_VELOCIDADE_MEDIA number(38, 6),
    VL_AREA_OPERACIONAL_M2 number(38, 6),
    FG_STATUS varchar(1),
    ETL_BATCH_ID varchar,
    BI_CREATED_AT timestamp_ntz,
    BI_UPDATED_AT timestamp_ntz,
    constraint UK_DS_SX_DETALHES_OPERACAO_F unique (
        ID_CLIENTE,
        DT_DIA_FECHAMENTO,
        DATA,
        HORA,
        CD_EQUIPAMENTO,
        CD_GRUPO_EQUIPAMENTO,
        CD_OPERACAO,
        CD_OPERACAO_CB,
        CD_ORDEM_SERVICO,
        CD_UNIDADE,
        CD_REGIONAL,
        CD_CORPORATIVO,
        CD_FAZENDA,
        CD_ZONA,
        CD_TALHAO,
        CD_MISSAO,
        CD_ESTADO
    )
);
